export const STEP_INFO = [
  "Entering key information about your business will allow the tool to generate relevant suggestions for your brand. Entering your industry is mandatory, but adding a slogan is optional (but recommended).",
  "Choosing the right icon is crucial as it will appear in your logo and in many other items of your kit. If you decide to change it, you can always go back.",
  "Picking the right font is crucial to communicate the energy of your brand: do you prefer it more serious and straightforward? Entertaining and fun? Rounded and welcoming?",
  "Choose a primary color that will be displayed across your assets.",
];

export const TOTAL_STEPS = 6;

export enum ONBOARDING_STEP_ENUM {
  BUSINESS_INFO = 0,
  ICON,
  FONT,
  COLOR,
  LOGO,
  BRAND_KIT,
}

export const AVAILABLE_FONTS = [
  "font-sans",
  "font-noto",
  "font-italic",
  "font-serif",
  "font-bold",
  "font-mono",
  "font-courier",
];

export const AVALIABLE_COLORS = [
  "#FF5733",
  "#F25D50",
  "#E64E40",
  "#FC4A1A",
  "#FF85A2",
  "#FF5E78",
  "#E32636",
  "#FF5349",
  "#F64A8A",
  "#FF6F61",
  "#E2062C",
  "#FF3030",
  "#FF4040",
  "#FF6B6B",
  "#E91E63",
  "#FF69B4",
  "#FF00CC",
  "#FF338D",
  "#F778A1",
  "#FA72FC",
  "#EAC117",
  "#F7E7CE",
  "#EAB33B",
  "#FFD700",
  "#FFEA00",
  "#FFB7C5",
  "#E68FAC",
  "#FF91A4",
  "#D16587",
  "#FA8072",
  "#FF6E4A",
  "#FF4500",
  "#FF7256",
  "#FF6347",
  "#FFA07A",
  "#FF4040",
  "#F7DC6F",
  "#FFD700",
  "#E7C697",
  "#FFE4B5",
  "#F4A460",
  "#E9967A",
  "#FFA500",
  "#FFA54F",
  "#F0E68C",
  "#FFFF00",
  "#FFD700",
  "#FDD017",
  "#FFF8DC",
  "#FFE4E1",
  "#F08080",
  "#FFA07A",
  "#E6E6FA",
  "#F4A460",
  "#FFFACD",
  "#E0FFFF",
  "#F5DEB3",
  "#FFDEAD",
  "#FFFFE0",
  "#FFF0F5",
];
